<a href="https://colab.research.google.com/github/Krisho1/Machine-Learning-Foundations-Math-Probability-Statistics-and-Computer-Science-Python-Codes-/blob/main/data_structure_and_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import torch
import pandas as pd
import matplotlib.pyplot as plt
import time
import random

##Constant Time

In [2]:
def take_first(my_list):
  return my_list[0]

In [3]:
short_list = [12,13,10,22,65,1]

In [4]:
tic = time.process_time()
first = take_first(short_list)
toc = time.process_time()

In [5]:
tic

10.668915696

In [6]:
first

12

In [7]:
toc

10.669064084

In [8]:
toc - tic


0.00014838800000127605

In [9]:
long_list = [42]* 10**8

In [10]:
len(long_list)

100000000

In [11]:
tic = time.process_time()
first = take_first(long_list)
toc = time.process_time()

In [12]:
first

42

In [13]:
toc-tic

0.00012050199999968925

In [14]:
list_length = [10**l for l in range(1,8)]
list_length

[10, 100, 1000, 10000, 100000, 1000000, 10000000]

In [15]:
constant_time = []


for l in list_length:
  lst = [42]*l
  tic = time.process_time()
  first = take_first(lst)
  toc = time.process_time()
  constant_time.append(toc-tic)

In [16]:
constant_df  =pd.DataFrame(list(zip(list_length,constant_time)), columns= ['n', 'time'])
constant_df

n          time
0        10  5.445000e-06
1       100  7.690000e-07
2      1000  8.580000e-07
3     10000  8.710000e-07
4    100000  2.021000e-06
5   1000000  5.855050e-04
6  10000000  1.007480e-04

## Linear

In [17]:
def find_max(my_list):
  max_val = my_list[0];
  for val in my_list[1:]:
    if val > max_val:
      max_val = val
  return max_val

In [18]:
short_list

[12, 13, 10, 22, 65, 1]

In [19]:
tic = time.process_time()
max_val = find_max(short_list)
toc = time.process_time()

In [20]:
max_val

65

In [21]:
toc-tic

9.753700000025844e-05

In [22]:
tic = time.process_time()
max_val = find_max(long_list)
toc = time.process_time()

In [23]:
toc-tic

6.229690454

## List

In [24]:
t = [25,3,6]

In [25]:
t.append(23)

In [26]:
t

[25, 3, 6, 23]

In [27]:
t[2]

6

In [28]:
#t/2  No math operation on list

In [29]:
x = np.array([25,2,3])

In [30]:
x[2]

3

In [31]:
x/3

array([8.33333333, 0.66666667, 1.        ])

In [32]:
y = torch.tensor([[25,2,3],[5,4,33]])
y

tensor([[25,  2,  3],
        [ 5,  4, 33]])

In [33]:
y[0,2]

tensor(3)

In [34]:
y/2

tensor([[12.5000,  1.0000,  1.5000],
        [ 2.5000,  2.0000, 16.5000]])

In [35]:
x = np.append(x,26)

In [36]:
x

array([25,  2,  3, 26])

##Stack

In [37]:
s = []

In [38]:
s.append('5 of diamond')
s

['5 of diamond']

In [39]:
s.append('ace of spades')
s

['5 of diamond', 'ace of spades']

In [40]:
s.append('Jocker of Diamond')
s

['5 of diamond', 'ace of spades', 'Jocker of Diamond']

In [41]:
s.pop()
s

['5 of diamond', 'ace of spades']

##Searching and Sorting

Binary Search

In [42]:
b = np.array([25,33,66,3,7,2,8,9,2,33,567,3])
b

array([ 25,  33,  66,   3,   7,   2,   8,   9,   2,  33, 567,   3])

In [43]:
b.sort() #Uses Quick Sort
b

array([  2,   2,   3,   3,   7,   8,   9,  25,  33,  33,  66, 567])

In [44]:
def binary_search(array, value):

    low = 0
    high = len(array)-1

    while low <= high:
        midpoint = (low + high) // 2 # rounds down to nearest integer after division
        if value < array[midpoint]:
            high = midpoint-1
        elif value > array[midpoint]:
            low = midpoint+1
        else:
            return midpoint
    return -1



In [45]:
binary_search(b,2)

0

In [46]:
def recursive_binary_search(array, value, low, high):

    if low <= high:

        midpoint = (low + high) // 2

        if array[midpoint] == value:
            return midpoint
        elif array[midpoint] > value:
            return recursive_binary_search(array, value, low, midpoint-1)
        else:
            return recursive_binary_search(array, value, midpoint+1, high)
    else:
        return -1

In [47]:
recursive_binary_search(b,25,0,len(b)-1)

7

##Bubble Sort

In [48]:
bs = np.array([2,88,6,55,4,76,89,4,54,83])
bs

array([ 2, 88,  6, 55,  4, 76, 89,  4, 54, 83])

In [49]:
def bubblesort(array):
  n = len(array)-1
  for i in range(n):
    for j in range(0,n):
      if array[j]>array[j+1]:
        array[j],array[j+1] = array[j+1],array[j]
  return array

In [50]:
bubblesort(bs)

array([ 2,  4,  4,  6, 54, 55, 76, 83, 88, 89])

##Merge Sort

In [55]:
'''
def merge_sort(my_list):

  midpoint = len(my_list)//2

  left_half = my_list[:midpoint]
  right_half = my_list[midpoint +1:]

  #recursive till 2 elements left

  left_half = merge_sort(left_half)
  right_half = merge_sort(right_half)


  my_list = []

  while len(left_half) > 0 and len(right_half) > 0:
    if left_half[0] < right_half[0]:
      my_list.append(left_half.pop(0))
    else:
      my_list.append(right_half.pop(0))

  for i in left_half:
    my_list.append(i)
  for i in right_half:
    my_list.append(i)


  return my_list

'''



'\ndef merge_sort(my_list):\n\n  midpoint = len(my_list)//2 \n\n  left_half = my_list[:midpoint]\n  right_half = my_list[midpoint +1:]\n\n  #recursive till 2 elements left\n\n  left_half = merge_sort(left_half)\n  right_half = merge_sort(right_half)\n\n\n  my_list = []\n\n  while len(left_half) > 0 and len(right_half) > 0:\n    if left_half[0] < right_half[0]:\n      my_list.append(left_half.pop(0))\n    else:\n      my_list.append(right_half.pop(0))\n  \n  for i in left_half:\n    my_list.append(i)\n  for i in right_half:\n    my_list.append(i)\n  \n\n  return my_list\n  \n'

In [56]:
def merge_sort(my_list): # using list instead of array so we can .pop() (np arrays don't pop with built-in method)

    if len(my_list) > 1: # if length is 1, no need to sort (at deepest recursion, some will have len 1, others len 2)

        # 1. Halve:
        midpoint = len(my_list) // 2 # Note: This is ~O(log n) behavior
        left_half = my_list[:midpoint]
        right_half = my_list[midpoint:]

        # 2. Sort (recursively):
        left_half = merge_sort(left_half)
        right_half = merge_sort(right_half)

        my_list = []

        # 3. Merge:
        while len(left_half)>0 and len(right_half)>0: # Note: This inner loop exhibits ~O(n) behavior

            if left_half[0] < right_half[0]:
                my_list.append(left_half.pop(0)) # pop first element

            else: # 1st element of right half < 1st element of left
                my_list.append(right_half.pop(0))

        # If any elements remain from either half, they must be the largest value:
        for i in left_half:
            my_list.append(i)
        for i in right_half:
            my_list.append(i)

    return my_list

In [57]:
m = [2,5,7,87,3,55,22,0,44,56,88,99,100]

In [58]:
merge_sort(m)

[0, 2, 3, 5, 7, 22, 44, 55, 56, 87, 88, 99, 100]