<a href="https://colab.research.google.com/github/Krisho1/Machine-Learning-Foundations-Math-Probability-Statistics-and-Computer-Science-Python-Codes-/blob/main/introduction_to_liner_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scaler (Rank 0) Tensior

In [2]:
x = 25
x

25

In [3]:
type(x)

int

In [4]:
y =3

In [5]:
py_sum = x+y
py_sum

28

In [6]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

**Intro to Pythorch and tesnsor**

In [7]:
import torch

In [8]:
x_pt = torch.tensor(25, dtype = torch.float16)
x_pt

tensor(25., dtype=torch.float16)

In [9]:
x_pt.shape

torch.Size([])

In [10]:
import tensorflow as tf

In [11]:
x_tf = tf.Variable(25, dtype = tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [12]:
x_tf.shape

TensorShape([])

In [13]:
y_tf = tf.Variable(3,dtype = tf.int16)

In [14]:
tf_sum = x_tf + y_tf
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [15]:
tf_sum.numpy() #Automatically convert tensor to numpy array

28

In [16]:
type(tf_sum.numpy())

numpy.int16

# Vector Tensor (RANK 1 Tensor) using tensorflow, numpy

In [17]:
import numpy as np

In [18]:
x_np = np.array([25,22,21]) #dtype = np.float16
x_np

array([25, 22, 21])

In [19]:
len(x_np)

3

In [20]:
x_np.shape

(3,)

In [21]:
type(x_np)

numpy.ndarray

In [22]:
x_np[2]

21

In [23]:
type(x_np[0])

numpy.int64

In [24]:
y_np = np.array([[25,3,1]])

In [25]:
y_np.shape

(1, 3)

In [26]:
y_np_t = y_np.T

In [27]:
y_np_t


array([[25],
       [ 3],
       [ 1]])

In [28]:
y_np_t.shape

(3, 1)

**Zero Vector**

In [29]:
z=np.zeros(3)
z

array([0., 0., 0.])

In [30]:
x_vec_pt = torch.tensor([25,2,5])
x_vec_pt

tensor([25,  2,  5])

In [31]:
x_vec_ten = tf.Variable([25,2,1])
x_vec_ten

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  1], dtype=int32)>

# L2 NORM

In [32]:
x_np

array([25, 22, 21])

In [33]:
l2_norm = ((25**2 + 22**2 + 21**2)**(1/2))
l2_norm

39.370039370059054

In [34]:
np.linalg.norm(x_np)

39.370039370059054

# L1 Norm

In [35]:
l1_norm = np.abs(25)+np.abs(22)+np.abs(21)
l1_norm

68

# Sqared L2 Norm

In [36]:
l2_sqrd = (25**2 + 22**2 + 21**2)
l2_sqrd

1550

In [37]:
np.dot(x_np,x_np)

1550

# Max Norm

In [38]:
np.max([np.abs(25),np.abs(22),np.abs(21)])

25

# Orthogonal Vector

In [39]:
i = np.array([1,0])
i

array([1, 0])

In [40]:
j = np.array([0,1])
j

array([0, 1])

In [41]:
np.dot(i,j)

0

# Matrices (Rank 2 Tensor)

In [42]:
X = np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
X.shape

(3, 2)

In [44]:
X[:,0]

array([1, 3, 5])

In [45]:
X[1,:]

array([3, 4])

In [46]:
X[0:2,0:2]

array([[1, 2],
       [3, 4]])

PyTorch

In [47]:
X_ts = torch.tensor([[12,21],[23,32],[34,43]])
X_ts

tensor([[12, 21],
        [23, 32],
        [34, 43]])

In [48]:
X_ts.shape

torch.Size([3, 2])

In [49]:
X_ts[:,0]

tensor([12, 23, 34])

Tesorflow

In [50]:
X_tf = tf.Variable([[1,2],[3,4],[5,6]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [51]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [52]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [53]:
X_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

#Generic Tensor

In [54]:
images_pt = torch.zeros([32,28,28,2])

In [55]:
# images_pt

# Tensor Transformation

In [56]:
X_Org = np.array([[0,1],[1,2],[3,4]])
X_Org

array([[0, 1],
       [1, 2],
       [3, 4]])

In [57]:
X_Org.T

array([[0, 1, 3],
       [1, 2, 4]])

# Basic Mathametical operation

In [58]:
X_Org*2

array([[0, 2],
       [2, 4],
       [6, 8]])

In [59]:
X_Org+2

array([[2, 3],
       [3, 4],
       [5, 6]])

In [60]:
X_Org*2+2

array([[ 2,  4],
       [ 4,  6],
       [ 8, 10]])

X_Org(.)A || Element wise product

In [62]:
A = X_Org +2
A

array([[2, 3],
       [3, 4],
       [5, 6]])

In [63]:
X_Org + A

array([[ 2,  4],
       [ 4,  6],
       [ 8, 10]])

In [64]:
X_Org * A #Not matrix multiplication

array([[ 0,  3],
       [ 3,  8],
       [15, 24]])

#Reduction

In [65]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
X.sum()

21

In [68]:
X.sum(axis = 0) #Row Sum

array([ 9, 12])

In [69]:
X.sum(axis = 1) #Column Sum

array([ 3,  7, 11])

# Dot Product

In [73]:
x_np

array([25, 22, 21])

In [74]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [75]:
25*1 + 22*2 + 21*3

132

In [76]:
np.dot(x_np,y)

132

# Exercise

In [79]:
y_ex_t = np.array([[42,4,7,99],[-99,-3,17,22]])
y_ex_t

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [80]:
y_ex_t.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [84]:
x_ex_ewp = np.array([[25,10],[-2,1]])
y_ex_ewp = np.array([[-1,7],[10,8]])
x_ex_ewp


array([[25, 10],
       [-2,  1]])

In [83]:
y_ex_ewp

array([[-1,  7],
       [10,  8]])

In [85]:
x_ex_ewp * y_ex_ewp

array([[-25,  70],
       [-20,   8]])

In [86]:
w_ex = np.array([-1,2,-2])
x_ex = np.array([5,10,0])

np.dot(w_ex,x_ex)

15