<a href="https://colab.research.google.com/github/Krisho1/Machine-Learning-Foundations-Math-Probability-Statistics-and-Computer-Science-Python-Codes-/blob/main/introduction_to_liner_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scaler (Rank 0) Tensior

In [1]:
x = 25
x

25

In [2]:
type(x)

int

In [4]:
y =3

In [5]:
py_sum = x+y
py_sum

28

In [7]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

**Intro to Pythorch and tesnsor**

In [8]:
import torch

In [9]:
x_pt = torch.tensor(25, dtype = torch.float16)
x_pt

tensor(25., dtype=torch.float16)

In [11]:
x_pt.shape

torch.Size([])

In [12]:
import tensorflow as tf

In [14]:
x_tf = tf.Variable(25, dtype = tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [17]:
x_tf.shape

TensorShape([])

In [19]:
y_tf = tf.Variable(3,dtype = tf.int16)

In [20]:
tf_sum = x_tf + y_tf
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [21]:
tf_sum.numpy() #Automatically convert tensor to numpy array

28

In [22]:
type(tf_sum.numpy())

numpy.int16

# Vector Tensor (RANK 1 Tensor) using tensorflow, numpy

In [23]:
import numpy as np

In [25]:
x_np = np.array([25,22,21]) #dtype = np.float16
x_np

array([25, 22, 21])

In [27]:
len(x_np)

3

In [29]:
x_np.shape

(3,)

In [30]:
type(x_np)

numpy.ndarray

In [31]:
x_np[2]

21

In [32]:
type(x_np[0])

numpy.int64

In [33]:
y_np = np.array([[25,3,1]])

In [34]:
y_np.shape

(1, 3)

In [35]:
y_np_t = y_np.T

In [37]:
y_np_t


array([[25],
       [ 3],
       [ 1]])

In [38]:
y_np_t.shape

(3, 1)

**Zero Vector**

In [39]:
z=np.zeros(3)
z

array([0., 0., 0.])

In [40]:
x_vec_pt = torch.tensor([25,2,5])
x_vec_pt

tensor([25,  2,  5])

In [41]:
x_vec_ten = tf.Variable([25,2,1])
x_vec_ten

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  1], dtype=int32)>

# L2 NORM

In [42]:
x_np

array([25, 22, 21])

In [44]:
l2_norm = ((25**2 + 22**2 + 21**2)**(1/2))
l2_norm

39.370039370059054

In [45]:
np.linalg.norm(x_np)

39.370039370059054

# L1 Norm

In [46]:
l1_norm = np.abs(25)+np.abs(22)+np.abs(21)
l1_norm

68

# Sqared L2 Norm

In [47]:
l2_sqrd = (25**2 + 22**2 + 21**2)
l2_sqrd

1550

In [48]:
np.dot(x_np,x_np)

1550

# Max Norm

In [51]:
np.max([np.abs(25),np.abs(22),np.abs(21)])

25