<a href="https://colab.research.google.com/github/Krisho1/Machine-Learning-Foundations-Math-Probability-Statistics-and-Computer-Science-Python-Codes-/blob/main/Single_Point_Regression_Gradiant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Single Point Regression Equation
We will Calculate gradiant of quadratic cost w.r.to. straight line regression model, we will keep partial derivative as simple as possible limiting the model to handle single data point

In [1]:
import torch

In [2]:
xs = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7.])

In [3]:
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])

y = mx + c

In [5]:
def my_fxn(my_x, my_m, my_c):
  return my_m * my_x + my_c


In [6]:
m = torch.tensor([0.9]).requires_grad_()
m

tensor([0.9000], requires_grad=True)

In [7]:
c = torch.tensor([0.1]).requires_grad_()
c

tensor([0.1000], requires_grad=True)

In [8]:
i = 7 # Let's  take one data
x = xs[i]
y = ys[i]

In [9]:
x

tensor(7.)

In [10]:
y

tensor(-1.3700)

In [11]:
yhat = my_fxn(x, m, c)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

Compare yhat
C(Cost) = (yhat -y)**2

In [12]:
def squared_error(my_yhat,my_y):
  return (my_yhat-my_y)**2

In [14]:
C = squared_error(yhat,y)

In [15]:
C.backward()  # Use autodiff to find gradient of C w.r.to m and b

In [16]:
m.grad # partial derivative of C (dC)/(dm)

tensor([108.7800])

In [19]:
c.grad #Partial derivative of C w.r.to (dC)/(dc)

tensor([15.5400])

In [22]:
deltaC_by_deltam = 2*x*(yhat.item() - y) #(dC)/(dm) = 2x(yhat - y)
deltaC_by_deltam

tensor(108.7800)

In [23]:
deltaC_by_deltac = 2*(yhat.item()-y) #(dC)/(dc) = 2(yhat - y)
deltaC_by_deltac

tensor(15.5400)

In [26]:
gradiant = torch.tensor([[c.grad.item(),m.grad.item()]]).T
gradiant

tensor([[ 15.5400],
        [108.7800]])